exclude: [
  'README.md',
  '**/README.md',
  'Gemfile.lock',
  'GEMFILE',
  '.gitignore',
  'LICENSE',
  'script',
  'vendor'
]

repository: newjersey/taxation-mef-viewer
url: newjersey.github.io/taxation-mef-viewer
bucket_url: https://jachan-test-cors-public.s3.amazonaws.com