exclude: [
  'README.md',
  '**/README.md',
  'Gemfile.lock',
  'GEMFILE',
  '.gitignore',
  'LICENSE',
  'script',
  'vendor'
]

repository: newjersey/taxation-mef-viewer
url: https://newjersey.github.io

github:
  url: https://github.com/newjersey/taxation-mef-viewer/tree/main
  repository_url: https://github.com/newjersey/taxation-mef-viewer

bucket_url: https://jachan-test-cors-public.s3.amazonaws.com

