exclude: [
  'README.md',
  '**/README.md',
  'Gemfile.lock',
  'GEMFILE',
  '.gitignore',
  'LICENSE',
  'script',
  'vendor'
]

repository: newjersey/taxation-mef-viewer
github:
  url: https://newjersey.github.io/taxation-mef-viewer
  repository_url: https://github.com/newjersey/taxation-mef-viewer