exclude: [
  'README.md',
  '**/README.md',
  'Gemfile.lock',
  'GEMFILE',
  '.gitignore',
  'LICENSE',
  'script',
  'vendor'
]

github:
  url: https://github.com/newjersey/taxation-mef-viewer/tree/master
  repository_url: https://github.com/newjersey/taxation-mef-viewer
  repository_nwo: newjersey/taxation-mef-viewer

bucket_url: https://jachan-test-cors-public.s3.amazonaws.com

