exclude: [
  'README.md',
  '**/README.md',
  'Gemfile.lock',
  'GEMFILE',
  '.gitignore',
  'LICENSE',
  'script',
  'vendor'
]

repository: newjersey/taxation-mef-viewer
amplify_url: https://main.d213b2tcid8n28.amplifyapp.com
repository_url: https://github.com/newjersey/taxation-mef-viewer