exclude: [
  'README.md',
  '**/README.md',
  'Gemfile.lock',
  'GEMFILE',
  '.gitignore',
  'LICENSE',
  'script',
  'vendor'
]

repository: newjersey/taxation-mef-viewer
bucket_url: https://jachan-test-cors-public.s3.amazonaws.com
github:
  url: https://newjersey.github.io
  repository_url: https://github.com/newjersey/taxation-mef-viewer